{
 "title": "Miwifi",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "在线设备数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_uptime" }
   ]
  },
  {
   "title": "在线设备数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_online_device_amount" }
   ]
  },
  {
   "title": "历史连接设备数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_history_device_amount" }
   ]
  },
  {
   "title": "硬件信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "型号",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_hardware_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Mac 地址",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_cpu_info", "legendFormat": "{{core}}" }
     ]
    },
    {
     "title": "固件版本",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_hardware_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "固件类型",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_hardware_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "SN",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_hardware_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "CPU 核数",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_cpu_info", "legendFormat": "{{core}}" }
     ]
    },
    {
     "title": "CPU频率",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_cpu_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "内存类型",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_memory_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "内存总量",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_memory_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "内存频率",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "miwifi_memory_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "WAN 信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "WAN 连接类型",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_wan_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAN 账户",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_wan_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAN 密码",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_wan_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "外网 IPV4 地址",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_ipv4", "legendFormat": "{{core}}" }
   ]
  },
  {
   "title": "外网 IPV6 地址",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_ipv6", "legendFormat": "{{core}}" }
   ]
  },
  { "title": "路由器信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "WAN 网速",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "miwifi_wan_download_speed", "legendFormat": "下载速度" },
    { "expr": "miwifi_wan_upload_speed", "legendFormat": "上传速度" },
    { "legendFormat": "上传速度" }
   ]
  },
  {
   "title": "CPU 负载",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "miwifi_cpu_load_percent", "legendFormat": "{{router_mac}}" }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "miwifi_memory_usage_percent", "legendFormat": "内存使用率" },
    { "expr": "miwifi_memory_usage", "legendFormat": "内存占用" }
   ]
  },
  { "title": "设备信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "下载流量统计",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_device_download_traffic", "legendFormat": "{{device_name}}({{ip}})" }
   ]
  },
  {
   "title": "上传流量统计",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_device_upload_traffic", "legendFormat": "{{device_name}}({{ip}})" }
   ]
  },
  {
   "title": "设备在线时间",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_device_online_time", "legendFormat": "{{device_name}}({{ip}})" }
   ]
  },
  {
   "title": "设备上传网速",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "miwifi_device_upload_speed", "legendFormat": "{{device_name}}({{ip}})" }
   ]
  },
  {
   "title": "设备下载网速",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "miwifi_device_download_speed", "legendFormat": "{{device_name}}({{ip}})" }
   ]
  }
 ]
}